### ISSUE TITLE
Syntax highlighter + Autocomplete of arguments does not work in MSVCV 17.12

### ISSUE THREAD

**Issue by timeester3648** [Sedeniono/VSDoxyHighlighter#6]
In this new update of MSVC, the extensions stopped working, only the autocomplete for initial commands (like \brief or \param, but without the names of the arguments of the function).

**All** sytax highlighting stopped. All features worked completely fine in 17.11 and before. I assume this is because some changes on Microsoft's end most likely.

**Comment by Sedeniono** [comment]
@timeester3648 Thanks for the report! Fortunately, fixing it was trivial. I just released v1.7.1 of the extension. It is available on [GitHub](https://github.com/Sedeniono/VSDoxyHighlighter/releases/tag/v1.7.1) and on the [VS marketplace](https://marketplace.visualstudio.com/items?itemName=Sedenion.VSDoxyHighlighter). Depending on your Visual Studio settings, it might get updated automatically.

Also, I welcome stars on GitHub and ratings on the marketplace 😉
